sudo: required
language: c
services:
  - docker
 
env:
  - LOCAL_NAME=docker-4dn-hic_local REMOTE_NAME=duplexa/4dn-hic

install:
  - docker build -t $LOCAL_NAME .

script:
  - source tests/tests.sh

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ $TRAVIS_PULL_REQUEST ]; then
        docker tag $LOCAL_NAME $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
        docker push $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
      else 
        docker tag $LOCAL_NAME $REMOTE_NAME:latest;
        docker push $REMOTE_NAME:latest;
      fi
    fi
  - echo 'good'
  - date
