sudo: required
language: c python
python: 2.7
os: linux
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - docker
 
env:
  - LOCAL_NAME=docker-4dn-hic_local REMOTE_NAME=duplexa/4dn-hic

install:
  - sudo pip install schema_salad
  - sudo pip install git+https://github.com/SooLee/cwltool.git  # cwltool
  - docker build -t $LOCAL_NAME .;

before_script:
  - if [ "$TRAVIS_PULL_REQUEST" != false ]; then
       docker tag $LOCAL_NAME $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
    else
       docker tag $LOCAL_NAME $REMOTE_NAME:$TRAVIS_BRANCH;
    fi;

script:
  - source tests/tests.sh > /dev/null
  - source tests/tests_cwl_all.sh > /dev/null

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ "$TRAVIS_PULL_REQUEST" != false ]; then
        docker tag $LOCAL_NAME $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
        docker push $REMOTE_NAME:$TRAVIS_PULL_REQUEST_BRANCH;
      else 
        docker tag $LOCAL_NAME $REMOTE_NAME:latest;
        docker push $REMOTE_NAME:latest;
      fi
    fi
  - echo 'good'
  - date
