#!/bin/bash
tmpDir=$(mktemp -d /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/execution/tmp.XXXXXX)
chmod 777 $tmpDir
export _JAVA_OPTIONS=-Djava.io.tmpdir=$tmpDir
export TMPDIR=$tmpDir

(
cd /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/execution
run-bwa-mem.sh /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/inputs/Users/soo/git/pipelines-cwl/tests/test_files/SRR1658650_R1.h40.fastq.gz /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/inputs/Users/soo/git/pipelines-cwl/tests/test_files/SRR1658650_R2.h40.fastq.gz /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/inputs/Users/soo/git/pipelines-cwl/tests/test_files/hg38.MTonly.bwaIndex.tgz out 8 .
)
echo $? > /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/execution/rc.tmp
(
cd /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/execution

)
sync
mv /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/execution/rc.tmp /cromwell-executions/bwa_mem/f107526c-44fb-47d5-a701-926544a7d9c8/call-bwa_mem_step/execution/rc
